// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThieuNhiTT.Api.Models;

#nullable disable

namespace ThieuNhiTT.Api.Migrations
{
    [DbContext(typeof(TNContext))]
    partial class TNContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThieuNhiTT.Api.Models.HiepDoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GiaoHat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LienDoanId")
                        .HasColumnType("int");

                    b.Property<string>("TenHiepDoan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HiepDoans");
                });

            modelBuilder.Entity("ThieuNhiTT.Api.Models.XuDoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GiaoXu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HiepDoanId")
                        .HasColumnType("int");

                    b.Property<string>("TenXuDoan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("XuDoans");
                });
#pragma warning restore 612, 618
        }
    }
}
